language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.1.5
  - DJANGO_VERSION=1.11.14
branches:
  only:
    - master
# Start services.
services:
  - postgresql
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements
  - pip install python-coveralls
before_script:
  - psql -c "CREATE DATABASE mcre;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --noinput
# command to run tests
script:
  - pytest
after_success:
  - coveralls